<?php

namespace App\Http\Requests;

class CharacterDataRequest extends BaseRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'account_id' => 'integer|nullable',
            'name' => 'string|max:64|nullable',
            'last_name' => 'string|max:64|nullable',
            'title' => 'string|max:32|nullable',
            'suffix' => 'string|max:32|nullable',
            'zone_id' => 'integer|nullable',
            'zone_instance' => 'integer|nullable',
            'y' => 'numeric|nullable',
            'x' => 'numeric|nullable',
            'z' => 'numeric|nullable',
            'heading' => 'numeric|nullable',
            'gender' => 'integer|nullable',
            'race' => 'integer|nullable',
            'class' => 'integer|nullable',
            'level' => 'integer|nullable',
            'deity' => 'integer|nullable',
            'birthday' => 'integer|nullable',
            'last_login' => 'integer|nullable',
            'time_played' => 'integer|nullable',
            'level2' => 'integer|nullable',
            'anon' => 'integer|nullable',
            'gm' => 'integer|nullable',
            'face' => 'integer|nullable',
            'hair_color' => 'integer|nullable',
            'hair_style' => 'integer|nullable',
            'beard' => 'integer|nullable',
            'beard_color' => 'integer|nullable',
            'eye_color_1' => 'integer|nullable',
            'eye_color_2' => 'integer|nullable',
            'drakkin_heritage' => 'integer|nullable',
            'drakkin_tattoo' => 'integer|nullable',
            'drakkin_details' => 'integer|nullable',
            'ability_time_seconds' => 'integer|nullable',
            'ability_number' => 'integer|nullable',
            'ability_time_minutes' => 'integer|nullable',
            'ability_time_hours' => 'integer|nullable',
            'exp' => 'integer|nullable',
            'exp_enabled' => 'integer|nullable',
            'aa_points_spent' => 'integer|nullable',
            'aa_exp' => 'integer|nullable',
            'aa_points' => 'integer|nullable',
            'group_leadership_exp' => 'integer|nullable',
            'raid_leadership_exp' => 'integer|nullable',
            'group_leadership_points' => 'integer|nullable',
            'raid_leadership_points' => 'integer|nullable',
            'points' => 'integer|nullable',
            'cur_hp' => 'integer|nullable',
            'mana' => 'integer|nullable',
            'endurance' => 'integer|nullable',
            'intoxication' => 'integer|nullable',
            'str' => 'integer|nullable',
            'sta' => 'integer|nullable',
            'cha' => 'integer|nullable',
            'dex' => 'integer|nullable',
            'int' => 'integer|nullable',
            'agi' => 'integer|nullable',
            'wis' => 'integer|nullable',
            'extra_haste' => 'integer|nullable',
            'zone_change_count' => 'integer|nullable',
            'toxicity' => 'integer|nullable',
            'hunger_level' => 'integer|nullable',
            'thirst_level' => 'integer|nullable',
            'ability_up' => 'integer|nullable',
            'ldon_points_guk' => 'integer|nullable',
            'ldon_points_mir' => 'integer|nullable',
            'ldon_points_mmc' => 'integer|nullable',
            'ldon_points_ruj' => 'integer|nullable',
            'ldon_points_tak' => 'integer|nullable',
            'ldon_points_available' => 'integer|nullable',
            'tribute_time_remaining' => 'integer|nullable',
            'career_tribute_points' => 'integer|nullable',
            'tribute_points' => 'integer|nullable',
            'tribute_active' => 'integer|nullable',
            'pvp_status' => 'integer|nullable',
            'pvp_kills' => 'integer|nullable',
            'pvp_deaths' => 'integer|nullable',
            'pvp_current_points' => 'integer|nullable',
            'pvp_career_points' => 'integer|nullable',
            'pvp_best_kill_streak' => 'integer|nullable',
            'pvp_worst_death_streak' => 'integer|nullable',
            'pvp_current_kill_streak' => 'integer|nullable',
            'pvp2' => 'integer|nullable',
            'pvp_type' => 'integer|nullable',
            'show_helm' => 'integer|nullable',
            'group_auto_consent' => 'integer|nullable',
            'raid_auto_consent' => 'integer|nullable',
            'guild_auto_consent' => 'integer|nullable',
            'leadership_exp_on' => 'integer|nullable',
            'RestTimer' => 'integer|nullable',
            'air_remaining' => 'integer|nullable',
            'autosplit_enabled' => 'integer|nullable',
            'lfp' => 'integer|nullable',
            'lfg' => 'integer|nullable',
            'mailkey' => 'nullable',
            'xtargets' => 'integer|nullable',
            'first_login' => 'integer|nullable',
            'ingame' => 'integer|nullable',
            'e_aa_effects' => 'integer|nullable',
            'e_percent_to_aa' => 'integer|nullable',
            'e_expended_aa_spent' => 'integer|nullable',
            'aa_points_spent_old' => 'integer|nullable',
            'aa_points_old' => 'integer|nullable',
            'e_last_invsnapshot' => 'integer|nullable',
            'deleted_at' => 'date|nullable',
            'illusion_block' => 'integer|nullable',
        ];
    }
}
