<?php

namespace App\Http\Requests;

class ZoneRequest extends BaseRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
            'zoneidnumber' => 'integer|min:0|max:2147483647|nullable',
            'version' => 'integer|min:0|max:255|nullable',
            'short_name' => 'string|max:32|nullable',
            'long_name' => 'required|string',
            'min_status' => 'integer|min:0|max:255|nullable',
            'map_file_name' => 'string|max:100|nullable',
            'note' => 'string|max:200|nullable',
            'min_expansion' => 'integer|min:-1|max:127|nullable',
            'max_expansion' => 'integer|min:-1|max:127|nullable',
            'content_flags' => 'string|max:100|nullable',
            'content_flags_disabled' => 'string|max:100|nullable',
            'expansion' => 'integer|min:0|max:127|nullable',
            'file_name' => 'string|max:16|nullable',
            'safe_x' => 'numeric|nullable',
            'safe_y' => 'numeric|nullable',
            'safe_z' => 'numeric|nullable',
            'safe_heading' => 'numeric|nullable',
            'graveyard_id' => 'numeric|nullable',
            'min_level' => 'integer|min:0|max:255|nullable',
            'max_level' => 'integer|min:0|max:255|nullable',
            'timezone' => 'integer|min:-2147483648|max:2147483647|nullable',
            'maxclients' => 'integer|min:-2147483648|max:2147483647|nullable',
            'ruleset' => 'integer|min:0|max:4294967295|nullable',
            'underworld' => 'numeric|nullable',
            'minclip' => 'numeric|nullable',
            'maxclip' => 'numeric|nullable',
            'fog_minclip' => 'numeric|nullable',
            'fog_maxclip' => 'numeric|nullable',
            'fog_blue' => 'integer|min:0|max:255|nullable',
            'fog_red' => 'integer|min:0|max:255|nullable',
            'fog_green' => 'integer|min:0|max:255|nullable',
            'sky' => 'integer|min:0|max:255|nullable',
            'ztype' => 'integer|min:0|max:255|nullable',
            'zone_exp_multiplier' => 'numeric|nullable',
            'walkspeed' => 'numeric|nullable',
            'time_type' => 'integer|min:0|max:255|nullable',
            'fog_red1' => 'integer|min:0|max:255|nullable',
            'fog_green1' => 'integer|min:0|max:255|nullable',
            'fog_blue1' => 'integer|min:0|max:255|nullable',
            'fog_minclip1' => 'numeric|nullable',
            'fog_maxclip1' => 'numeric|nullable',
            'fog_red2' => 'integer|min:0|max:255|nullable',
            'fog_green2' => 'integer|min:0|max:255|nullable',
            'fog_blue2' => 'integer|min:0|max:255|nullable',
            'fog_minclip2' => 'numeric|nullable',
            'fog_maxclip2' => 'numeric|nullable',
            'fog_red3' => 'integer|min:0|max:255|nullable',
            'fog_green3' => 'integer|min:0|max:255|nullable',
            'fog_blue3' => 'integer|min:0|max:255|nullable',
            'fog_minclip3' => 'numeric|nullable',
            'fog_maxclip3' => 'numeric|nullable',
            'fog_red4' => 'integer|min:0|max:255|nullable',
            'fog_green4' => 'integer|min:0|max:255|nullable',
            'fog_blue4' => 'integer|min:0|max:255|nullable',
            'fog_minclip4' => 'numeric|nullable',
            'fog_maxclip4' => 'numeric|nullable',
            'fog_density' => 'numeric|nullable',
            'flag_needed' => 'string|max:128|nullable',
            'canbind' => 'integer|min:-128|max:127|nullable',
            'cancombat' => 'integer|min:-128|max:127|nullable',
            'canlevitate' => 'integer|min:-128|max:127|nullable',
            'castoutdoor' => 'integer|min:-128|max:127|nullable',
            'hotzone' => 'integer|min:0|max:255|nullable',
            'insttype' => 'boolean|nullable',
            'shutdowndelay' => 'integer|min:0|max:18446744073709551615|nullable',
            'peqzone' => 'integer|min:-128|max:127|nullable',
            'bypass_expansion_check' => 'integer|min:-128|max:127|nullable',
            'suspendbuffs' => 'boolean|nullable',
            'rain_chance1' => 'integer|min:0|max:100|nullable',
            'rain_chance2' => 'integer|min:0|max:100|nullable',
            'rain_chance3' => 'integer|min:0|max:100|nullable',
            'rain_chance4' => 'integer|min:0|max:100|nullable',
            'rain_duration1' => 'integer|min:0|max:100|nullable',
            'rain_duration2' => 'integer|min:0|max:100|nullable',
            'rain_duration3' => 'integer|min:0|max:100|nullable',
            'rain_duration4' => 'integer|min:0|max:100|nullable',
            'snow_chance1' => 'integer|min:0|max:100|nullable',
            'snow_chance2' => 'integer|min:0|max:100|nullable',
            'snow_chance3' => 'integer|min:0|max:100|nullable',
            'snow_chance4' => 'integer|min:0|max:100|nullable',
            'snow_duration1' => 'integer|min:0|max:100|nullable',
            'snow_duration2' => 'integer|min:0|max:100|nullable',
            'snow_duration3' => 'integer|min:0|max:100|nullable',
            'snow_duration4' => 'integer|min:0|max:100|nullable',
            'gravity' => 'numeric|nullable',
            'type' => 'integer|min:0|max:5|nullable',
            'skylock' => 'integer|min:-128|max:127|nullable',
            'fast_regen_hp' => 'integer|min:-2147483648|max:2147483647|nullable',
            'fast_regen_mana' => 'integer|min:-2147483648|max:2147483647|nullable',
            'fast_regen_endurance' => 'integer|min:-2147483648|max:2147483647|nullable',
            'npc_max_aggro_dist' => 'integer|min:-2147483648|max:2147483647|nullable',
            'client_update_range' => 'integer|min:-2147483648|max:2147483647|nullable',
            'underworld_teleport_index' => 'integer|min:-2147483648|max:2147483647|nullable',
            'lava_damage' => 'integer|min:-2147483648|max:2147483647|nullable',
            'min_lava_damage' => 'integer|min:-2147483648|max:2147483647|nullable',
            'idle_when_empty' => 'boolean|nullable',
            'seconds_before_idle' => 'integer|min:0|max:4294967295|nullable',
            'shard_at_player_count' => 'integer|min:-2147483648|max:2147483647|nullable',
        ];
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'zoneidnumber' => $this->defaultInt('zoneidnumber', 0),
            'version' => $this->defaultInt('version', 0),
            'short_name' => $this->defaultString('short_name', ''),
            'long_name' => $this->defaultString('long_name', ''),
            'min_status' => $this->defaultInt('min_status', 0),
            'map_file_name' => $this->defaultString('map_file_name', ''),
            'note' => $this->defaultString('note', ''),
            'min_expansion' => $this->defaultInt('min_expansion', -1),
            'max_expansion' => $this->defaultInt('max_expansion', -1),
            'content_flags' => $this->defaultString('content_flags', ''),
            'content_flags_disabled' => $this->defaultString('content_flags_disabled', ''),
            'expansion' => $this->defaultInt('expansion', 0),
            'file_name' => $this->defaultString('file_name', ''),
            'safe_x' => $this->defaultFloat('safe_x', 0),
            'safe_y' => $this->defaultFloat('safe_y', 0),
            'safe_z' => $this->defaultFloat('safe_z', 0),
            'safe_heading' => $this->defaultFloat('safe_heading', 0),
            'graveyard_id' => $this->defaultFloat('graveyard_id', 0),
            'min_level' => $this->defaultInt('min_level', 0),
            'max_level' => $this->defaultInt('max_level', 255),
            'timezone' => $this->defaultInt('timezone', 0),
            'maxclients' => $this->defaultInt('maxclients', 0),
            'ruleset' => $this->defaultInt('ruleset', 0),
            'underworld' => $this->defaultFloat('underworld', 0),
            'minclip' => $this->defaultFloat('minclip', 450),
            'maxclip' => $this->defaultFloat('maxclip', 450),
            'fog_minclip' => $this->defaultFloat('fog_minclip', 450),
            'fog_maxclip' => $this->defaultFloat('fog_maxclip', 450),
            'fog_blue' => $this->defaultInt('fog_blue', 0),
            'fog_red' => $this->defaultInt('fog_red', 0),
            'fog_green' => $this->defaultInt('fog_green', 0),
            'sky' => $this->defaultInt('sky', 1),
            'ztype' => $this->defaultInt('ztype', 1),
            'zone_exp_multiplier' => $this->defaultFloat('zone_exp_multiplier', 0.00),
            'walkspeed' => $this->defaultFloat('walkspeed', 0.4),
            'time_type' => $this->defaultInt('time_type', 2),
            'fog_red1' => $this->defaultInt('fog_red1', 0),
            'fog_green1' => $this->defaultInt('fog_green1', 0),
            'fog_blue1' => $this->defaultInt('fog_blue1', 0),
            'fog_minclip1' => $this->defaultFloat('fog_minclip1', 450),
            'fog_maxclip1' => $this->defaultFloat('fog_maxclip1', 450),
            'fog_red2' => $this->defaultInt('fog_red2', 0),
            'fog_green2' => $this->defaultInt('fog_green2', 0),
            'fog_blue2' => $this->defaultInt('fog_blue2', 0),
            'fog_minclip2' => $this->defaultFloat('fog_minclip2', 450),
            'fog_maxclip2' => $this->defaultFloat('fog_maxclip2', 450),
            'fog_red3' => $this->defaultInt('fog_red3', 0),
            'fog_green3' => $this->defaultInt('fog_green3', 0),
            'fog_blue3' => $this->defaultInt('fog_blue3', 0),
            'fog_minclip3' => $this->defaultFloat('fog_minclip3', 450),
            'fog_maxclip3' => $this->defaultFloat('fog_maxclip3', 450),
            'fog_red4' => $this->defaultInt('fog_red4', 0),
            'fog_green4' => $this->defaultInt('fog_green4', 0),
            'fog_blue4' => $this->defaultInt('fog_blue4', 0),
            'fog_minclip4' => $this->defaultFloat('fog_minclip4', 450),
            'fog_maxclip4' => $this->defaultFloat('fog_maxclip4', 450),
            'fog_density' => $this->defaultFloat('fog_density', 0),
            'flag_needed' => $this->defaultString('flag_needed', ''),
            'canbind' => $this->defaultInt('canbind', 1),
            'cancombat' => $this->defaultInt('cancombat', 1),
            'canlevitate' => $this->defaultInt('canlevitate', 1),
            'castoutdoor' => $this->defaultInt('castoutdoor', 1),
            'hotzone' => $this->defaultInt('hotzone', 0),
            'insttype' => $this->defaultInt('insttype', 0),
            'shutdowndelay' => $this->defaultInt('shutdowndelay', 5000),
            'peqzone' => $this->defaultInt('peqzone', 1),
            'bypass_expansion_check' => $this->defaultInt('bypass_expansion_check', 0),
            'suspendbuffs' => $this->defaultInt('suspendbuffs', 0),
            'rain_chance1' => $this->defaultInt('rain_chance1', 0),
            'rain_chance2' => $this->defaultInt('rain_chance2', 0),
            'rain_chance3' => $this->defaultInt('rain_chance3', 0),
            'rain_chance4' => $this->defaultInt('rain_chance4', 0),
            'rain_duration1' => $this->defaultInt('rain_duration1', 0),
            'rain_duration2' => $this->defaultInt('rain_duration2', 0),
            'rain_duration3' => $this->defaultInt('rain_duration3', 0),
            'rain_duration4' => $this->defaultInt('rain_duration4', 0),
            'snow_chance1' => $this->defaultInt('snow_chance1', 0),
            'snow_chance2' => $this->defaultInt('snow_chance2', 0),
            'snow_chance3' => $this->defaultInt('snow_chance3', 0),
            'snow_chance4' => $this->defaultInt('snow_chance4', 0),
            'snow_duration1' => $this->defaultInt('snow_duration1', 0),
            'snow_duration2' => $this->defaultInt('snow_duration2', 0),
            'snow_duration3' => $this->defaultInt('snow_duration3', 0),
            'snow_duration4' => $this->defaultInt('snow_duration4', 0),
            'gravity' => $this->defaultFloat('gravity', 0.4),
            'type' => $this->defaultInt('type', 0),
            'skylock' => $this->defaultInt('skylock', 0),
            'fast_regen_hp' => $this->defaultInt('fast_regen_hp', 180),
            'fast_regen_mana' => $this->defaultInt('fast_regen_mana', 180),
            'fast_regen_endurance' => $this->defaultInt('fast_regen_endurance', 180),
            'npc_max_aggro_dist' => $this->defaultInt('npc_max_aggro_dist', 600),
            'client_update_range' => $this->defaultInt('client_update_range', 600),
            'underworld_teleport_index' => $this->defaultInt('underworld_teleport_index', 0),
            'lava_damage' => $this->defaultInt('lava_damage', 50),
            'min_lava_damage' => $this->defaultInt('min_lava_damage', 10),
            'idle_when_empty' => $this->defaultInt('idle_when_empty', 1),
            'seconds_before_idle' => $this->defaultInt('seconds_before_idle', 60),
            'shard_at_player_count' => $this->defaultInt('shard_at_player_count', 0),
        ]);
    }
}
